language: c

compiler: gcc

# Travis uses Ubuntu 12.04 (Precise) for builds by default, which is too
# old and missing the SDL2 packages, so use Trusty instead.
sudo: required
dist: trusty

# TODO: Remove old SDL library dependencies once sdl2-branch is merged.
addons:
    apt:
        packages:
        - libsdl2-dev
        - libsdl2-mixer-dev
        - libsdl2-net-dev
        - libsdl2-image-dev
        - libsamplerate0-dev
        - libsdl1.2-dev
        - libsdl-mixer1.2-dev
        - libsdl-net1.2-dev
        - libpng-dev

script: ./autogen.sh && make && make install DESTDIR=/tmp/whatever && make dist

branches:
    only:
    - master
    - sdl2-branch

